package taaasks;

import java.awt.Color;
import javax.swing.JLabel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author teobourloglou
 */
public class Task extends javax.swing.JPanel {
    private int taskId;
    /**
     * Creates new form TaskPanel
     */
    public Task() {
        initComponents();
    }

    public int getId() {
        return this.taskId;
    }
    
    public void setId(int id) {
        this.taskId = id;
    }
    
    public void setTitle(String text) {
        taskTitle.setText(text);
    }
    
    public void setDescription(String text) {
        taskDescription.setText(text);
    }
    
    public void setTag(String text) {
        taskTag.setText(text);
    }
    
    public void setTagBackground(int r, int g, int b) {
        taskTag.setBackground(new Color(r,g,b));
        taskTag.setOpaque(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskTitle = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        taskTag = new javax.swing.JLabel();
        taskDescription = new javax.swing.JLabel();

        setBackground(new java.awt.Color(54, 53, 59));
        setMaximumSize(new java.awt.Dimension(280, 150));
        setPreferredSize(new java.awt.Dimension(280, 123));

        taskTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        taskTitle.setForeground(new java.awt.Color(255, 255, 255));
        taskTitle.setText("Task Title");

        deleteButton.setBackground(new java.awt.Color(54, 53, 59));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taaasks/media/trash.png"))); // NOI18N
        deleteButton.setToolTipText("Delete task");
        deleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 53, 59)));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        taskTag.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        taskTag.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskTag.setText("tag");

        taskDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        taskDescription.setForeground(new java.awt.Color(204, 203, 211));
        taskDescription.setText("Task Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taskDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taskTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(deleteButton)
                    .addComponent(taskTag, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel taskDescription;
    private javax.swing.JLabel taskTag;
    private javax.swing.JLabel taskTitle;
    // End of variables declaration//GEN-END:variables
}
