/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taaasks;

/**
 *
 * @author teobourloglou
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        exploreButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Taaasks");
        setBackground(new java.awt.Color(247, 247, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 20));
        setPreferredSize(new java.awt.Dimension(500, 450));
        setResizable(false);

        title.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(29, 38, 51));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Welcome");

        description.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        description.setForeground(new java.awt.Color(87, 115, 153));
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description.setText("Stay organized, stay ahead");

        text1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        text1.setForeground(new java.awt.Color(87, 115, 153));
        text1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taaasks/media/playlist-add(1).png"))); // NOI18N
        text1.setText("Create a new project");

        text2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        text2.setForeground(new java.awt.Color(87, 115, 153));
        text2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taaasks/media/list-check(1).png"))); // NOI18N
        text2.setText("Add your tasks");

        text3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        text3.setForeground(new java.awt.Color(87, 115, 153));
        text3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taaasks/media/trending-up(1).png"))); // NOI18N
        text3.setText("Boost your productivity");

        exploreButton.setBackground(new java.awt.Color(87, 115, 153));
        exploreButton.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        exploreButton.setForeground(new java.awt.Color(87, 115, 153));
        exploreButton.setText("Start Exploring");
        exploreButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(87, 115, 153), 1, true));
        exploreButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exploreButton.setFocusable(false);
        exploreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exploreButton.setRequestFocusEnabled(false);
        exploreButton.setRolloverEnabled(false);
        exploreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exploreButtonActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taaasks/media/layers-subtract.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(exploreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(description)
                .addGap(52, 52, 52)
                .addComponent(text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text3)
                .addGap(18, 18, 18)
                .addComponent(exploreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exploreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exploreButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Create create = new Create();
        create.setVisible(true);        
        create.errorMessageHide();
    }//GEN-LAST:event_exploreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JButton exploreButton;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
